### ISSUE TITLE
Mention legends of runeterra and/or LoR in Readme

### ISSUE THREAD

**Issue by skyegecko** [dneto/sai-scout#1]
Haiya,

This may seem like a really minor thing, but I was looking for Sai Scout in google and had trouble finding it because using keywords like "lor" doesn't help google find its way here. Do you think you could include something like this in the description?

**Comment by dneto** [comment]
Sorry, I was in vacations and totally forgot about this issue. 
I've added Legends of Runeterra references in both README and project description. Hope this helps the project to be more easy to find.

I'll close this issue, but feel free to reopen :)
